language: android

addons:
    apt:
        packages:
        - libgd2-xpm
        - ia32-libs
        - ia32-libs-multiarch

android:
   components:
   - platform-tools
   - android-23
   - build-tools-23.0.1
   - extra

jdk: oraclejdk7

notifications:
  email: false

before_install:

  - source .travis/env.sh

script:
  - bash .travis/build.sh
