language: android

addons:
    apt:
        packages:
        - libgd2-xpm
        - ia32-libs
        - ia32-libs-multiarch

android:
   components:
   - platform-tools
   - android-23
   - build-tools-23.0.1
   - extra

jdk: oraclejdk7

notifications:
  email: false

before_install:
  - openssl aes-256-cbc -K $encrypted_361f359e2b86_key -iv $encrypted_361f359e2b86_iv -in release.jks.enc -out release.jks -d
  - source .travis/env.sh

script:
  - bash .travis/build.sh

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file:
    - "$HOME/Finance-debug-v$VERSION.apk"
    - "$HOME/Finance-release-v$VERSION.apk"
  skip_cleanup: true
  on:
    tags: true

env:
    global:
        - secure: "BIrgkemCAd3QQyTW/QajYHcRwqdUDg5HO6uuNb3XJOWs92Yx2eQSmhlW/KH24qlLZxhe7s71r5hcoL0nCY/+r/cAITCL82SnewXagszcgmmOn/zJcZEIEpwci83wtRts5ZmhpNtO6r5qNQfeOP3uKSggMvyBpKVHa90C3M0pxIdsMGTIjtdUuvjypOYwt5dPthI7G77LfLe/ZRVAlo3lf8KSwr7O275OACZWY96qzu5p5NigBPHzRELAcNxLnODQlZMJ2ExouiFTC447BpQDoADa+Uux2fKmYRRvPa32l02vrCdJFnKX8EpCeFCUWn7cp6NBfUR5nNHyN5WtQ24ikGXyzMNl13T/DAvwWfm9wmeLCfvlmQ3JNvJvNHqKYql6akwwf+t5DvhxRzffU0pTMmrXXC5U22Tde07AQmGX2JU+5A5B9tf/5039mrV1u2llyRfj1Yv63S2CE8diPK49lHMMrgUW1Y8IG4gZu5q2ONFnf6mkj6DCwrYMPJNYgwzX0jFSnn4tb3x2orljhuYkios+21tITkm3164V8C5QImWkwwkagQG1kBwCnjEkkd3mtwPiOB9Mj0jP7bc8i+zjhr0Q7HmgjamYXb+Z8A2Uxj0oLlgRKlcZ9g906YmtJqHXo2baOBKEN9ovAxOdLCE7CJjTX597gUDGY8Vcylvwyss="
        - secure: "l3j1Zi1DZTy8z9NzVSfbIDi/CeDjsSIW+9MyCOqsDT9L0BPXgeT0RkEuYig2OZ/ZdE4vjT5sKKBHbtRoLAWaLkMHsGtU5ktziAwyhuSY2bqtToLm585OV47MnMXFt5CcBkacVqYc35mX9TlfNmFQtkrX9Guz6vT69S2x9lu+HOCxugSmoucxOl/V4T9tXsqqfK5wLgt6ACtVH2mdT1sXPlQ3pDsCtgdAqDNcDYo0JEArFQfzmPmsRmdj41aSp2a3gbuPbSRE6ox93c7l52fzf1ai0IDS4QerizSQ2wwGdLvhgLHkI3DkUic7ZQnzKVmCU8nSSAQ71iUP6dTfWXzfiRzp/rByie6q/nqg1RDsDY9JRwcFE3EQusAeLegPShaSC2kSjnqVrSZxxEZZ6jLfycUaD+6TmMdvgYC7YVNN5S+JrfHikcgAm+gDM2Xo3SLfMmt5et6ssiWp3vsZ+WiXvAwFr5mYT4BCSFBl2YvMO2f2KIl0B+mCNMY+Amf9Cl3KbAXRabW6qhhYsfi7g1BPStdU4TOggiwx5ZprWw+Qmx35vqVg8KQztuVNrSHg1BKBMyjg787+4laCAJi9J65rwFKX71HLonuXcZ2xv6DwmYbeZw63mBdb9JANQUup/99JJY/tEYS8fyapyBuruH11Dr7wKSU3qNgiRbG63Y3Q1rU="
        - secure: "UKdFX44sI/h+Yl2Bbk1Z9XHS9FYSKz0bs4nnQkXb8KCYR9cWQZg7RjmjKCU8SMQy7AvHKtdVlv9rbsoh5i7fePBZPMB5XENrCmF8vTfQyuIR/jb4mgEIQ60KV61+ImGjwVgrJBmruP2CSDheN/N8LM8noDrSbosO6qCiyCZOrheuJX6zZZc1o+LB1hqvgF+USYKA2FB85+Tmi2isKhYBi3WSPexOJyuyaxF5B/r35Pqi23iNnJMrlamNdq/hMW6bdbumAjr4Dj+Zok1s7utdgwcEgFhVlCydTrd2rUv6bfxxAFoDslohr0pkdlWCRpnQGluRJuI/bspA2wYhU6PlcPnsAd9uukpqZCn/2jhlhTVEMB83pBwfTTAxrLHyaLedwqrwcqrmwtDwlcwgIH20G+LMe0Z+CZOscP5PH0zmiYWOBq8NjzjIGbGAsK0NCtvoP5Urn7N58bsVKIipefZXxHhAAr2eBp4Zwdne24AR+i00cY4ZTKnLF+A20BmrI9OLiAyBMYvru/A0eq9k99uZrVcoucSTcuRdNwvLaN51v0UQn5iTo0Vxjp0WvyOnwc6QjxDd4jtcEogkcOLwV1/yqkjnG8eSTYejYgMRJ7pIJ49fJcume7wMMjSDnnKdZw8wtiCS4iu75f0MmuwyoNaA2srWj2mTNKrNqqWylc7hOaU="
        - secure: "qXpYHeUwW+lbb7rRsEiBL+iw0+zB/PjX/YisKZqOt3b2ZANg80qA9MzTnGQmX+WT8VMpVNrRWFF/S8qD0dKkc9mlhcMKZHQyUdy+Bdy1QWCfEanEh3rZfuGZEjhOhJf3i/7gBYSSl4QVHjnhdy9NIjzwq2+obSIBKhXoQOqc0hBG5EPinon7MsWdEEulKDFSDCejC0BaQxuRrrg2klCqGizXgpF285yv767gNICT0Py0uToWZecqr5/8iJZtsEtecySfSUySEwQBQjVLowpbChQ9Qbplf2iDMkVoQQjvyJ7pggzXDucBviLLnAkv11cFWCU0swuW96HC30CBgZ42NAznntCXYr1XTXiqcrOrQADnJEuRO6QKQKYyCwCER5BQD6kl33hOd1Kk6nd1fcIuMYmtxnlzvAisjEkMXjCGsQ9QtU5XR2G5kd46bl44n2IXmmwteXEUXf1V5pBB/OCAkdmVcScpkVifWW11u88aoCJguo2uRqUhmPxftWpsYwMr6sp7/BB+iUAQz7Iv61CG5nznsm0nmYML1i2z215tz4ubwYARx5K31mibY3PC7ppfaSk3XKRygFQ6eLz7osNtONMo6yqRtN+RFy4U+ATZmcOpnbPrekotdWcxks+YoU9EckXZ2jW5ZflD0ourppipJ75u0fHdTeFvMQe962vSBJ8="
